name: 'LINE Notify'
description: 'LINE Notify for GitHub Actions'
inputs:
  access_token:
    description: 'LINE Access Token'
    required: true
  message:
    description: 'Message'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
